-- Queue of candidate push events produced by the firehose worker and claimed by Nest.
CREATE TABLE push_event_queue (
    id BIGSERIAL PRIMARY KEY,
    recipient_did TEXT NOT NULL,
    actor_did TEXT NOT NULL,
    notification_type TEXT NOT NULL,
    event_cid TEXT NOT NULL,
    event_path TEXT NOT NULL,
    subject_uri TEXT,
    thread_root_uri TEXT,
    event_record_json JSONB NOT NULL,
    event_timestamp BIGINT NOT NULL,
    dedupe_key TEXT NOT NULL,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    claimed_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (dedupe_key)
);

CREATE INDEX idx_push_event_queue_claimable
    ON push_event_queue (available_at, id)
    WHERE claimed_at IS NULL AND delivered_at IS NULL;

CREATE INDEX idx_push_event_queue_recipient
    ON push_event_queue (recipient_did, created_at DESC);

CREATE INDEX idx_push_event_queue_subject
    ON push_event_queue (subject_uri);

CREATE INDEX idx_push_event_queue_thread_root
    ON push_event_queue (thread_root_uri)
    WHERE thread_root_uri IS NOT NULL;

COMMENT ON TABLE push_event_queue IS
'Candidate push events generated by catbird-firehose for Nest to filter, claim, and deliver';
